- name: Deploy
  hosts: tag_reddit-app
  tasks:
  - name: Fetch the latest version of application code
    git:
      repo: 'https://github.com/Artemmkin/reddit.git'
      dest: /home/appuser/reddit
      version: monolith
    tags: deploy-tag
    notify: restart puma

  - name: Bundle install
    bundler:
      state: present
      chdir: /home/appuser/reddit
    tags: deploy-tag
    notify: restart puma

  handlers:
  - name: restart puma
    become: true
    systemd: name=puma state=restarted
